In [2]:
import numpy as np
import pandas as pd

In [3]:
Breast = pd.read_csv(r"C:\Users\HARISH\Downloads\Breast-Cancer-Prediction-Model-using-Machine-Learning-main\breast cancer.csv")
Breast.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [4]:
Breast.diagnosis.value_counts()

diagnosis
B    357
M    212
Name: count, dtype: int64

In [5]:
Breast.shape

(569, 33)

In [6]:
Breast.isnull().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed:

In [7]:
Breast.duplicated().sum()

0

In [8]:
Breast.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [9]:
Breast.drop('Unnamed: 32',axis=1,inplace=True)

In [10]:
Breast.diagnosis= Breast.diagnosis.map({"M":1,"B":0})

In [11]:
Breast.diagnosis.value_counts()

diagnosis
0    357
1    212
Name: count, dtype: int64

In [12]:
# splitting data into training and testing sets
x=Breast.drop('diagnosis',axis=1)
y=Breast.diagnosis

In [13]:
x.shape

(569, 31)

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [16]:
X_train.shape

(455, 31)

In [17]:
X_test.shape

(114, 31)

In [18]:
y_train.shape

(455,)

In [19]:
y_test.shape

(114,)

In [20]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()

In [41]:
sc.fit(X_train)

StandardScaler()

In [43]:
X_train =sc.transform(X_train)
X_test =sc.transform(X_test)

In [45]:
X_train

array([[-0.23712699, -1.44075296, -0.43531947, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [-0.23702031,  1.97409619,  1.73302577, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-0.23712907, -1.39998202, -1.24962228, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [-0.17630431,  0.04880192, -0.55500086, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.23675669, -0.03896885,  0.10207345, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.2371006 , -0.54860557,  0.31327591, ..., -0.61102866,
        -0.3345212 , -0.84628745]])

In [ ]:
# TRAINING MODEL

In [47]:
from sklearn.linear_model import LogisticRegression
lg = LogisticRegression()

In [49]:
lg.fit(X_train,y_train)
y_pred = lg.predict(X_test)

In [51]:
y_pred

array([0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1], dtype=int64)

In [55]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9736842105263158

In [ ]:
# PREDICTION SYSTEM

In [71]:
input_text=(-0.23687964,  0.04030797, -0.23819718, -0.02725804, -0.06001243,
       -2.15592988, -0.98104496, -0.80810952, -0.90850515, -0.64095228,
       -0.95764719, -0.60815306, -0.9862056 , -0.57868202, -0.4135118 ,
       -1.25105866, -0.63839765, -0.68618822, -1.05785631, -1.16912304,
       -0.66932816, -0.00314261, -0.0455055 , -0.03908819, -0.10102666,
       -1.6082721 , -0.23276225, -0.56459233, -0.59585724, -0.42646531,
       -0.39868387)
np_df =np.asarray(input_text)
predictiont=lg.predict(np_df.reshape(1,-1))

if predictiont[0] ==1:
    print("Cancrous")

else:
    print("Not Cancrous")

Not Cancrous


In [69]:
X_train[18]

array([-0.23687964,  0.04030797, -0.23819718, -0.02725804, -0.06001243,
       -2.15592988, -0.98104496, -0.80810952, -0.90850515, -0.64095228,
       -0.95764719, -0.60815306, -0.9862056 , -0.57868202, -0.4135118 ,
       -1.25105866, -0.63839765, -0.68618822, -1.05785631, -1.16912304,
       -0.66932816, -0.00314261, -0.0455055 , -0.03908819, -0.10102666,
       -1.6082721 , -0.23276225, -0.56459233, -0.59585724, -0.42646531,
       -0.39868387])

In [75]:
import pickle
pickle.dump(lg,open('Model.pkl','wb'))